# Generated by Django 4.0.5 on 2022-07-01 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='NightOut.creator')),
                ('member', models.CharField(max_length=400)),
                ('event_name', models.CharField(max_length=50)),
                ('location1', models.CharField(max_length=50, null=True)),
                ('location2', models.CharField(max_length=50, null=True)),
                ('location3', models.CharField(max_length=50, null=True)),
                ('time1', models.DateTimeField(default=django.utils.timezone.now)),
                ('time2', models.DateTimeField(default=django.utils.timezone.now)),
                ('time3', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='NightOut.event')),
                ('location1_ranking', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default='0')),
                ('location2_ranking', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default='0')),
                ('location3_ranking', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default='0')),
                ('time1_ranking', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default='0')),
                ('time2_ranking', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default='0')),
                ('time3_ranking', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default='0')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
