# Generated by Django 4.0.5 on 2022-07-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NightOut', '0002_alter_creator_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='creator',
        ),
        migrations.AddField(
            model_name='creator',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
