# Generated by Django 4.0.5 on 2022-07-01 23:13

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NightOut', '0005_remove_creator_email_remove_voting_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.OneToOneField(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='NightOut.creator'),
        ),
    ]
